# https://github.com/nodejs/docker-node/issues/740#issuecomment-458545074
FROM node:16.4.1-alpine

USER node 
RUN mkdir -p /home/node/app
WORKDIR /home/node/app

COPY --chown=node:node ./package.json ./

RUN npm install --silent 

COPY --chown=node:node . .

CMD ["npm", "run", "start"]
