version: '3'
services: 
  nginx: 
    depends_on: 
      - api 
      - client
    restart: always
    image: alinisarahmed/docker-multi-nginx
    mem_limit: 128m
    hostname: nginx
    ports: 
      - '80:80'
  api: 
    image: alinisarahmed/docker-multi-server
    mem_limit: 128m
    hostname: api
    environment: 
      - REDIS_HOST=$REDIS_HOST
      - REDIS_PORT=$REDIS_PORT
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  client: 
    image: alinisarahmed/docker-multi-client
    mem_limit: 128m
    hostname: client
  worker: 
    image: alinisarhmed/docker-multi-worker
    mem_limit: 128m
    hostname: worker
    environment: 
      - REDIS_HOST=$REDIS_HOST 
      - REDIS_PORT=$REDIS_PORT

